### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [avnu-labs/tree-sitter-cairo#2]
Using this page https://meimporta.eu/tree-sitter/json2ebnf.html we can get a navigable railroad diagram for tree-sitter grammars like this project.

See also https://github.com/tree-sitter/tree-sitter/issues/2268 .

Cheers !

**Comment by Frostweeds** [comment]
Thanks ! Didn't know about that, that's great ! I'll put that in place a soon as possible :)
